### ISSUE TITLE
A typo in lsq_classopath

### ISSUE THREAD

**Issue by puyun1990** [Hua-Zhou/SparseReg#2]
In the Line 9 of lsq_classopath, it seems to be A*beta<=b instead of A*beta=b.
Best,

**Comment by Hua-Zhou** [comment]
@brgaines 
https://github.com/Hua-Zhou/SparseReg/blob/4ddb9cb80f9fccdb5d8439a52854cc2fe826d397/lsq_classopath.m#L9

**Comment by Hua-Zhou** [comment]
Good catch. Thanks @puyun1990

**Comment by brgaines** [comment]
Thanks for letting us know, @puyun1990!  Also, thanks for taking care of it @Hua-Zhou
