### ISSUE TITLE
general loss function? penalty for each variable?

### ISSUE THREAD

**Issue by cwliu007** [Hua-Zhou/SparseReg#3]
Hi, 

Thanks for developing this useful package for public! I have two questions:
Does SparseReg allow for a general loss function (or any likelihood function)? I read your paper (Eq. 8; https://arxiv.org/pdf/1611.01511.pdf) that denotes it as f(x). I also wonder whether I can specify the penalty parameter for each variable?

**Comment by Hua-Zhou** [comment]
For your first question, currently SparseReg only implemented least squares and GLM (generalized linear model) loss function. We are open for suggestion if you want to implement specific loss function.

The question to your second question is yes. You can specify weights for each parameter using the `weights` optional argument. For example, 
```matlab
lsq_sparsereg(X, y, lambda, 'weights', wt)
```
solves the lasso regression with penalty 
```matlab
lambda * sum(wt .* abs(beta))
```

**Comment by cwliu007** [comment]
Thanks for the reply, Dr. Zhou,

I am looking for a package that allows for constrained lasso and a general likelihood function simultaneously. As you may know, L1General package allows user to specify a general likelihood but not the constrained lasso (https://www.cs.ubc.ca/~schmidtm/Software/L1General.html) If I understand correctly, the SparseReg allows for constrained lasso but not for a general likelihood. I would like to do both tasks at the same time in order to develop a package for latent variable models by using some lasso package as a kernel. So I hope the likelihood function can be user-specific. It will be great if SparseReg can do the job in the future. Thanks!

**Comment by Hua-Zhou** [comment]
Your suggestion of general loss + contained lasso makes sense. Have you checked the FASTA (http://www.cs.umd.edu/~tomg/projects/fasta/) or TFOCS (http://cvxr.com/tfocs/) packages? They might serve your purpose.

**Comment by cwliu007** [comment]
Hi Dr. Zhou,

Thanks for the information! They looks quite useful.

**Comment by Hua-Zhou** [comment]
Glad to help.
